index:
  path: /
  controller: App\Controller\SecurityController::login

logout:
  path: logout
  controller: App\Controller\SecurityController::logout

register:
  path: Inscription
  controller: App\Controller\RegistrationController::register
home:
  path: Dashboard
  controller: App\Controller\HomeController::index
Userslist:
  path: Dashboard/Userslist
  controller: App\Controller\HomeController::userslist
Edituser:
  path: Dashboard/Edituser/{id}
  controller: App\Controller\HomeController::edituser
Entreprise:
  path: Entreprise/new
  controller: App\Controller\EntrepriseController::new
EntrepriseList:
  path: Entreprise/list
  controller: App\Controller\EntrepriseController::list
